import random

ROASTS = [
    "You're proof that even evolution takes a break sometimes. 😆",
    "I'd agree with you, but then we’d both be wrong. 😂",
    "Your secrets are safe with me. I never even listen when you tell me them. 😜",
    "I’m not saying you’re slow, but your brain has buffering issues. 🧠💀",
    "If I had a dollar for every smart thing you said, I'd be broke. 😎",
    "You bring everyone so much joy… when you leave the room. 😆",
    "Your WiFi signal is stronger than your personality. 📡😂",
    "You're like a cloud. When you disappear, it's a beautiful day. ☀️😜",
    "Your brain must be on vacation, because it’s clearly out of office. 🏖️🤦‍♂️",
    "You have something on your chin… no, the third one down. 😜",
    "You're like a penny—two-faced and not worth much. 🪙😂",
    "You have something on your face… oh wait, that’s just your personality. 😏",
    "If I wanted to hear from someone useless, I’d turn on airplane mode and talk to Siri. ✈️🤖",
    "Your opinions are like a broken pencil… pointless. ✏️💀",
    "You remind me of a cloud. You make everything gloomy. ☁️😆",
    "I’d explain it to you, but I left my crayons at home. 🖍️🤡",
    "You're slower than a dial-up internet connection in 1999. 📶🐢",
    "Your jokes are so dry, even the Sahara is jealous. 🌵💀",
    "The only thing you run fast is your mouth. 🏃‍♂️😂",
    "You bring everyone so much joy… when you log off. 😂",
    "You're like a cloud storage plan—full of junk and running out of space. ☁️💀",
    "Your presence is like a Windows error—unexpected and highly annoying. 🖥️😆",
    "You’re proof that the internet sometimes connects to the wrong server. 🌐🤡",
    "You’d be more useful as a loading screen—at least then, people would expect delays. ⏳😂",
    "Your brain is like a pop-up ad—unwanted and ignored. 🧠🚫",
    "You're not lazy, you're just highly motivated to do nothing. 🛏️💀",
    "Your personality is like a ringtone from 2005—outdated and embarrassing. 📞😂",
    "You’re like a pizza with no toppings—completely unnecessary. 🍕😆",
    "Your thinking speed makes glaciers jealous. ❄️🐢",
    "You're the human version of an expired coupon—completely useless. 🛒💀",
    "You're like a WiFi signal in a basement—weak and disappointing. 📶😂",
    "Your sense of humor is like a vending machine—out of order. 🤖🚫",
    "If brains were fuel, you wouldn’t have enough to power a flashlight. 🔦😂",
    "Your conversations are like software updates—nobody wants them, but they keep coming. 🔄😆",
    "You must be solar-powered, because you shut down when logic is needed. ☀️💀",
    "You're like a notification from an unknown app—confusing and unnecessary. 📱😆",
    "If intelligence was a mobile plan, yours would have limited data. 📉😂",
    "Your logic is like a QR code on a broken phone—completely unreadable. 📱💀",
    "You're the human version of a CAPTCHA—hard to understand and frustrating. 🤖😆",
    "Your thoughts load slower than a website with bad hosting. 🖥️⏳",
    "You're like an unskippable ad—nobody wants you, but they have to deal with you. 📢😂",
    "Your brain must be a rental—someone else is using it right now. 🧠💀",
    "You're the reason people check if their WiFi is working. 📶😂",
    "Your problem-solving skills make a broken calculator look smart. 🧮💀",
    "You’re like a phone with a dead battery—completely useless when needed. 📵😂",
    "Your logic is like a broken compass—it never points in the right direction. 🧭💀",
    "You’d make a great NPC in a game—because you never think for yourself. 🎮😂",
    "You're like a spellcheck error—everyone notices but doesn’t want to correct you. 📝💀",
    "Your ideas make a 404 error look intelligent. 🌐❌",
    "You're the human version of lag—frustrating and slowing everything down. ⏳😂",
    "Your personality is like a factory reset—completely wiped of anything useful. 🔄💀",
    "You're the reason people double-check their volume settings—just to mute you. 🔊🚫",
    "Your common sense is like a corrupted file—missing and unrecoverable. 🖥️💀",
    "You're like a broken printer—never delivering anything of value. 🖨️😂",
    "Your decision-making is like a coin flip—50% chance of disaster. 🪙💀",
    "Your brain has more bugs than a beta version of Windows. 🖥️🐞",
    "You're like an old meme—no one finds you funny anymore. 🤡😂",
    "Your thoughts are like a clickbait article—misleading and disappointing. 📰💀",
    "Your comebacks are like an old router—weak and outdated. 📶😂",
    "You must be exhausted from running away from common sense. 🧠💀",
    "You have something in common with a speed bump—everyone tries to avoid you. 🛑😆",
    "If ignorance is bliss, you must be the happiest person alive. 🤣",
    "You should carry a plant around to replace the oxygen you waste. 🌿💀",
    "Your insults are like your grades—below average. 📉😂",
    "I’d call you a tool, but even tools have a purpose. 🔨😆",
    "Your life is like a browser with 20 tabs open, and you're still clueless. 🌐🤡",
    "You're proof that natural selection sometimes takes a day off. 🦴😂",
    "You're so slow, even a snail would tell you to hurry up. 🐌⏳",
    "Your words are like expired milk—nobody wants them. 🥛🤮",
    "You bring people together… because they all agree you're annoying. 😜",
    "If common sense was currency, you'd be broke. 💸😂",
    "Your confidence is impressive for someone who’s wrong 99% of the time. 🤡",
    "You are a walking 'low battery' warning. 🔋💀",
    "I’d give you a comeback, but it looks like nature already did. 🌳😂",
    "Your face makes onions cry. 🧅💀",
    "You're like a software update—nobody wants you, but we have to deal with you. 🤖😂",
    "Your best quality is your WiFi connection, and even that’s unstable. 📶😆",
    "You’re the human version of a typo. ✏️💀",
    "You're so extra, even Excel can't handle you. 📊😂",
    "Your logic is like a screen door on a submarine—completely useless. 🚢💀",
    "I’d explain sarcasm to you, but I’d need hand puppets. 🖐️😆",
    "You're the reason even Google has questions. 🤔🔍",
    "Your comebacks are like Windows updates—slow and unnecessary. 🖥️😂",
    "You bring people together… because they all agree they don’t like you. 😜",
    "You're like a Bluetooth connection—unreliable and unnecessary. 🎧💀",
    "Your voice is like a fire alarm, except it only warns people to leave the conversation. 🔥🚨",
    "You have so much free time, even time itself is confused. ⏳😂",
    "Your life has more buffering than a bad internet connection. 📶💀",
    "You're proof that sometimes, auto-correct is smarter than the user. 📱😂",
]

def get_savage_reply():
    return random.choice(ROASTS)
